model = "gpt-5-codex"
hide_agent_reasoning = true
network_access = true
[tools]
web_search = true

[mcp_servers.remotion-docs]
command = "npx"
args = ["-y", "@remotion/mcp@latest"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]
